apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata: 
  name: ocpv-payx-performance
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
    - data: |
        # This is a number of settings taken from other profiles, including:
        # throughput-performance
        # network-throughput
        # latency-performance
        # network-latency
        [main]
        summary=Fibre Channel (FC/FCoE) — IOPS-optimized
        description=Random/OLTP FC LUNs: Smaller readahead, deeper queue depth; mq-deadline scheduler.
        include=openshift-control-plane
        [cpu]
        governor=performance
        energy_perf_bias=performance
        min_perf_pct=100
        energy_performance_preference=performance
        force_latency=cstate.id_no_zero:1|3
        boost=1
        [acpi]
        platform_profile=performance
        [sysfs-scheduler]
        type=sysfs
        /sys/block/dm-*/queue/scheduler=mq-deadline
        /sys/block/sd*/queue/scheduler=mq-deadline
        [sysfs-nr-requests]
        type=sysfs
        /sys/block/dm-*/queue/nr_requests=256
        /sys/block/sd*/queue/nr_requests=256
        [sysfs-queue-depth]
        type=sysfs
        /sys/block/sd*/device/queue_depth=256
        [sysfs-add-random]
        type=sysfs
        /sys/block/dm-*/queue/add_random=0
        /sys/block/sd*/queue/add_random=0
        [sysfs-max-sectors-kb]
        type=sysfs
        /sys/block/dm-*/queue/max_sectors_kb=4096
        /sys/block/sd*/queue/max_sectors_kb=4096
        [sysfs-read-ahead-kb]
        type=sysfs
        /sys/block/dm-*/queue/read_ahead_kb=128
        /sys/block/sd*/queue/read_ahead_kb=128
        [sysfs-rotational]
        type=sysfs
        /sys/block/dm-*/queue/rotational=0
        /sys/block/sd*/queue/rotational=0
        [sysfs-rq-affinity]
        type=sysfs
        /sys/block/dm-*/queue/rq_affinity=2
        /sys/block/sd*/queue/rq_affinity=2
        [sysfs-write-cache]
        type=sysfs
        # Adjusting write cache on slave devices to multipath devices does not effect
        # raw dm device; must set on virtual device.
        /sys/devices/virtual/block/dm-*/queue/write_cache=write through
        /sys/block/sd*/queue/write_cache=write through
        [sysctl]
        # If a workload mostly uses anonymous memory and it hits this limit, the entire
        # working set is buffered for I/O, and any more write buffering would require
        # swapping, so it's time to throttle writes until I/O can catch up.  Workloads
        # that mostly use file mappings may be able to use even higher values.
        # The generator of dirty data starts writeback at this percentage (system default
        # is 20%)
        vm.dirty_ratio=10
        # Start background writeback (via writeback threads) at this percentage (system
        # default is 10%)
        vm.dirty_background_ratio=3
        # Don't swap unless absolutely needed.
        vm.swappiness=0
        [sysctl-network-throughput]
        type=sysctl
        # Increase kernel buffer size maximums.  Currently this seems only necessary at 40Gb speeds.
        # The buffer tuning values below do not account for any potential hugepage allocation.
        # Ensure that you do not oversubscribe system memory.
        net.ipv4.tcp_rmem="4096 131072 16777216"
        net.ipv4.tcp_wmem="4096 16384 16777216"
        [sysctl-network-latency]
        type=sysctl
        net.core.busy_read=50
        net.core.busy_poll=50
        net.ipv4.tcp_fastopen=3
        net.ipv4.tcp_slow_start_after_idle=0
        kernel.numa_balancing=0
        kernel.hung_task_timeout_secs=600
        kernel.nmi_watchdog=0
        vm.stat_interval=10
        kernel.timer_migration=0 
      name: ocpv-payx-performance
  recommend:
    - match:
        - label: tuned.openshift.io/ocpv-payx-performance 
      priority: 20
      profile: ocpv-payx-performance